version: '3.8'

services:
  db:
    container_name: db
    build:
      context: ./db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p root"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure:10

  back:
    container_name: back
    build:
      context: ./back
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure:10

  react:
    container_name: react-app
    build:
      context: ./front-desktop
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
    depends_on:
      - "spring-boot"